In [46]:
import praw
import pandas as pd
import datetime as dt
import logging
import numpy as np
from numpy import random
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
import re
from bs4 import BeautifulSoup
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import classification_report

In [71]:
def logisticreg(X_train, X_test, y_train, y_test):
    from sklearn.linear_model import LogisticRegression
    logmodel = LogisticRegression(C=1e3)
    logmodel.fit(X_train,y_train)
    predictions = logmodel.predict(X_test)
    from sklearn.metrics import classification_report
    print(classification_report(y_test,predictions))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,predictions))
    score = logmodel.score(X_test, y_test)
    print(score)

In [78]:
def train_test(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

#     print("Results of Logistic Regression")
#     logisticreg(X_train, X_test, y_train, y_test)
    
#     print("svm")
#     svm(X_train, X_test, y_train, y_test)
    print('random forest')
    rand(X_train, X_test, y_train, y_test)

In [79]:

df =pd.read_csv('../Datasets/ML_vars/0001.csv')
for i in range(1,18):
    stri=''
    if i<=8:
        stri+='0'+str(i)+'0'+str(i+1)
    elif i==9:
        stri+='0'+str(i)+str(i+1)
    else:
        stri+=str(i)+str(i+1)    
    temp_df=pd.read_csv('../Datasets/ML_vars/{}.csv'.format(stri))
    df=pd.concat([df,temp_df],sort =False)

In [80]:
df

,Unnamed: 0,Date,HomeTeam,AwayTeam,FTHG,FTAG,HomeResult,AwayResult,scoredhome,scoredaway,concededhome,concededaway,winshome,winsaway
0,0,19/08/00,Charlton,Man City,4,0,1.0,0.0,4,0,0,4,1.0,0.0
1,1,19/08/00,Chelsea,West Ham,4,2,1.0,0.0,4,2,2,4,1.0,0.0
2,2,19/08/00,Coventry,Middlesbrough,1,3,0.0,1.0,1,3,3,1,0.0,1.0
3,3,19/08/00,Derby,Southampton,2,2,0.5,0.5,2,2,2,2,0.5,0.5
4,4,19/08/00,Leeds,Everton,2,0,1.0,0.0,2,0,0,2,1.0,0.0
5,5,19/08/00,Leicester,Aston Villa,0,0,0.5,0.5,0,0,0,0,0.5,0.5
6,6,19/08/00,Liverpool,Bradford,1,0,1.0,0.0,1,0,0,1,1.0,0.0
7,7,19/08/00,Sunderland,Arsenal,1,0,1.0,0.0,1,0,0,1,1.0,0.0
8,8,19/08/00,Tottenham,Ipswich,3,1,1.0,0.0,3,1,1,3,1.0,0.0
9,9,20/08/00,Man United,Newcastle,2,0,1.0,0.0,2,0,0,2,1.0,0.0
10,10,21/08/00,Arsenal,Liverpool,2,0,1.0,0.0,2,0,0,2,1.0,0.0
11,11,22/08/00,Bradford,Chelsea,2,0,1.0,0.0,2,0,0,2,1.0,0.0
12,12,22/08/00,Ipswich,Man United,1,1,0.5,0.5,1,1,1,1,0.5,0.5
13,13,22/08/00,Middlesbrough,Tottenham,1,1,0.5,0.5,1,1,1,1,0.5,0.5
14,14,23/08/00,Everton,Charlton,3,0,1.0,0.0,3,0,0,3,1.0,0.0
15,15,23/08/00,Man City,Sunderland,4,2,1.0,0.0,4,2,2,4,1.0,0.0
16,16,23/08/00,Newcastle,Derby,3,2,1.0,0.0,3,2,2,3,1.0,0.0
17,17,23/08/00,Southampton,Coventry,1,2,0.0,1.0,1,2,2,1,0.0,1.0
18,18,23/08/00,West Ham,Leicester,0,1,0.0,1.0,0,1,1,0,0.0,1.0
19,19,26/08/00,Arsenal,Charlton,5,3,1.0,0.0,7,3,3,8,2.0,0.0
20,20,26/08/00,Bradford,Leicester,0,0,0.5,0.5,2,1,0,0,1.5,1.5
21,21,26/08/00,Everton,Derby,2,2,0.5,0.5,5,4,2,5,1.5,0.5
22,22,26/08/00,Ipswich,Sunderland,1,0,1.0,0.0,2,2,1,5,1.5,0.0
23,23,26/08/00,Man City,Coventry,1,2,0.0,1.0,5,4,4,2,1.0,2.0
24,24,26/08/00,Middlesbrough,Leeds,1,2,0.0,1.0,2,2,3,1,0.5,1.0
25,25,26/08/00,Newcastle,Tottenham,2,0,1.0,0.0,5,1,2,3,2.0,0.5
26,26,26/08/00,Southampton,Liverpool,3,3,0.5,0.5,4,3,5,5,0.5,0.5
27,27,26/08/00,West Ham,Man United,2,2,0.5,0.5,2,3,3,3,0.5,1.0
28,28,27/08/00,Aston Villa,Chelsea,1,1,0.5,0.5,1,1,1,3,0.5,0.5
29,29,05/09/00,Leeds,Man City,1,2,0.0,1.0,3,2,2,5,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,350,28/04/18,Swansea,Chelsea,0,1,0.0,1.0,16,32,21,19,7.5,11.5
351,351,29/04/18,Man United,Arsenal,2,1,1.0,0.0,37,18,9,28,15.0,5.0
352,352,29/04/18,West Ham,Man City,1,4,0.0,1.0,21,44,25,13,8.5,16.0
353,353,30/04/18,Tottenham,Watford,2,0,1.0,0.0,34,17,12,32,13.0,5.0
354,354,04/05/18,Brighton,Man United,1,0,1.0,0.0,24,30,25,19,11.0,11.5
355,355,05/05/18,Bournemouth,Swansea,1,0,1.0,0.0,26,11,30,32,9.5,5.0
356,356,05/05/18,Everton,Southampton,1,1,0.5,0.5,28,16,22,30,12.0,6.0
357,357,05/05/18,Leicester,West Ham,0,2,0.0,1.0,22,24,21,42,9.0,6.0
358,358,05/05/18,Stoke,Crystal Palace,1,2,0.0,1.0,20,16,30,28,7.5,7.0
359,359,05/05/18,Watford,Newcastle,2,1,1.0,0.0,27,18,31,29,10.0,6.0
360,360,05/05/18,West Brom,Tottenham,1,0,1.0,0.0,21,34,29,20,7.5,12.0
361,361,06/05/18,Arsenal,Burnley,5,0,1.0,0.0,54,20,20,22,16.0,10.5
362,362,06/05/18,Chelsea,Liverpool,1,0,1.0,0.0,29,39,15,28,12.5,11.5
363,363,06/05/18,Man City,Huddersfield,0,0,0.5,0.5,58,11,13,32,16.0,5.0
364,364,08/05/18,Swansea,Southampton,0,1,0.0,1.0,16,17,22,30,7.5,7.0
365,365,09/05/18,Chelsea,Huddersfield,1,1,0.5,0.5,30,12,16,33,13.0,5.5
366,366,09/05/18,Leicester,Arsenal,3,1,1.0,0.0,25,19,22,31,10.0,5.0
367,367,09/05/18,Man City,Brighton,3,1,1.0,0.0,61,10,14,25,17.0,4.5
368,368,09/05/18,Tottenham,Newcastle,1,0,1.0,0.0,35,18,12,30,14.0,6.0
369,369,10/05/18,West Ham,Man United,0,0,0.5,0.5,21,30,25,19,9.0,12.0
370,370,13/05/18,Burnley,Bournemouth,1,2,0.0,1.0,16,19,17,31,9.5,7.0
371,371,13/05/18,Crystal Palace,West Brom,2,0,1.0,0.0,29,10,27,27,9.5,5.0
372,372,13/05/18,Huddersfield,Arsenal,0,1,0.0,1.0,16,20,25,31,8.5,6.0
373,373,13/05/18,Liverpool,Brighton,4,0,1.0,0.0,45,10,10,29,15.5,4.5
374,374,13/05/18,Man United,Watford,1,0,1.0,0.0,38,17,9,33,16.0,5.0
375,375,13/05/18,Newcastle,Chelsea,3,0,1.0,0.0,21,32,17,22,10.0,11.5
376,376,13/05/18,Southampton,Man City,0,1,0.0,1.0,20,45,26,13,7.5,17.0
377,377,13/05/18,Swansea,Stoke,1,2,0.0,1.0,17,15,24,38,7.5,5.5
378,378,13/05/18,Tottenham,Leicester,5,4,1.0,0.0,40,31,16,38,15.0,7.5
379,379,13/05/18,West Ham,Everton,3,1,1.0,0.0,24,16,26,36,10.0,6.0

In [81]:
Home = pd.get_dummies(df['HomeTeam'],drop_first=True)
Away = pd.get_dummies(df['AwayTeam'],drop_first=True)
df.drop(['HomeTeam','AwayTeam'],axis=1,inplace=True)
df = pd.concat([df,Home,Away],axis=1)

In [82]:
df.columns

Index(['Unnamed: 0', 'Date', 'FTHG', 'FTAG', 'HomeResult', 'AwayResult',
       'scoredhome', 'scoredaway', 'concededhome', 'concededaway', 'winshome',
       'winsaway', 'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool',
       'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff',
       'Charlton', 'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton',
       'Fulham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester',
       'Liverpool', 'Man City', 'Man United', 'Middlesboro', 'Middlesbrough',
       'Newcastle', 'Norwich', 'Portsmouth', 'QPR', 'Reading',
       'Sheffield United', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
       'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wigan', 'Wolves',
       'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool', 'Bolton',
       'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff', 'Charlton',
       'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton', 'Fulham',
       'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester', 'Liverpool',
       'Man City', 'Man United', 'Middlesboro', 'Middlesbrough', 'Newcastle',
       'Norwich', 'Portsmouth', 'QPR', 'Reading', 'Sheffield United',
       'Southampton', 'Stoke', 'Sunderland', 'Swansea', 'Tottenham', 'Watford',
       'West Brom', 'West Ham', 'Wigan', 'Wolves'],
      dtype='object')

In [83]:
# X=df[['FTHG', 'FTAG', 'scoredhome', 'scoredaway', 'concededhome', 'concededaway',
#        'winshome', 'winsaway', 'Bournemouth', 'Brighton', 'Burnley', 'Cardiff',
#        'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Huddersfield',
#        'Leicester', 'Liverpool', 'Man City', 'Man United', 'Newcastle',
#        'Southampton', 'Tottenham', 'Watford', 'West Ham', 'Wolves',
#        'Bournemouth', 'Brighton', 'Burnley', 'Cardiff', 'Chelsea',
#        'Crystal Palace', 'Everton', 'Fulham', 'Huddersfield', 'Leicester',
#        'Liverpool', 'Man City', 'Man United', 'Newcastle', 'Southampton',
#        'Tottenham', 'Watford', 'West Ham', 'Wolves']]
X=df.drop(['Unnamed: 0', 'Date', 'HomeResult', 'AwayResult','FTHG','FTAG'],axis =1)

In [84]:
X.columns

Index(['scoredhome', 'scoredaway', 'concededhome', 'concededaway', 'winshome',
       'winsaway', 'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool',
       'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff',
       'Charlton', 'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton',
       'Fulham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester',
       'Liverpool', 'Man City', 'Man United', 'Middlesboro', 'Middlesbrough',
       'Newcastle', 'Norwich', 'Portsmouth', 'QPR', 'Reading',
       'Sheffield United', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
       'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wigan', 'Wolves',
       'Aston Villa', 'Birmingham', 'Blackburn', 'Blackpool', 'Bolton',
       'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff', 'Charlton',
       'Chelsea', 'Coventry', 'Crystal Palace', 'Derby', 'Everton', 'Fulham',
       'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester', 'Liverpool',
       'Man City', 'Man United', 'Middlesboro', 'Middlesbrough', 'Newcastle',
       'Norwich', 'Portsmouth', 'QPR', 'Reading', 'Sheffield United',
       'Southampton', 'Stoke', 'Sunderland', 'Swansea', 'Tottenham', 'Watford',
       'West Brom', 'West Ham', 'Wigan', 'Wolves'],
      dtype='object')

In [85]:
y=df[['HomeResult']]*10

In [86]:
y=y.astype(int)

In [87]:
def svm(X_train, X_test, y_train, y_test):
    from sklearn.svm import SVC
    from sklearn.metrics import accuracy_score

    clf = SVC(kernel='linear')
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))
    from sklearn.metrics import classification_report
    print(classification_report(y_test,y_pred))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,y_pred))
    score = logmodel.score(X_test, y_test)
    print(score)

In [98]:
def rand(X_train, X_test, y_train, y_test):
    from sklearn.ensemble import RandomForestClassifier

    #Create a Gaussian Classifier
    clf=RandomForestClassifier(n_estimators=100)
    #Train the model using the training sets y_pred=clf.predict(X_test)
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))
    from sklearn.metrics import classification_report
    print(classification_report(y_test,y_pred))
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test,y_pred))
    score = clf.score(X_test, y_test)
    print(score)

In [99]:
train_test(X,y)

random forest

/home/jushaan/Downloads/yes/lib/python3.7/site-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys

0.628167641325536
              precision    recall  f1-score   support

           0       0.62      0.64      0.63       589
           5       0.47      0.26      0.34       504
          10       0.67      0.81      0.73       959

    accuracy                           0.63      2052
   macro avg       0.59      0.57      0.57      2052
weighted avg       0.61      0.63      0.61      2052

[[378  67 144]
 [132 132 240]
 [ 96  84 779]]
0.628167641325536